urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import index

urlpatterns = [
    url(r'(?P<_evento>[-\w]+)/(?P<_content>[-\w]+)/$', index, name='index'),
    url(r'(?P<_evento>[-\w]+)/$', index, name='index'),
    ]

models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

ESCOLHA_FLUXO_TRABALHO = (
    ('publicado', 'Publicado'),
    ('retirado', 'Retirado'),
    ('privado', 'Privado'),
)

ESCOLHA_CATEGORIA = (
    ('sistema', 'Conteúdo do Sistema.'),
    ('publico', 'Conteúdo público.')
)

ESCOLHA_TARGET = (
    ('_self', 'Abrir o link no mesma janela em que foi clicado (é o padrão)'),
    ('_blank', 'Abrir o link em uma nova janela ou guia'),
    ('_parent', 'Abre o link vinculado no frame pai'),
    ('_top', 'Abre o link no corpo inteiro da janela'),
    ('_framename', 'Abre o link em um frame nomeado'),
)

ESCOLHA_GRUPO = (
    ('administradores', 'Administradores'),
    ('conteudista', 'Conteúdista'),
)

ESCOLHA_TIPO_CONTEUDO = (
    ('at_pagina', 'Página'),
    ('at_informe', 'Informe'),
    ('at_agenda', 'Agenda'),
    ('at_link', 'Link'),
    ('at_banner', 'Banner'),
    ('at_imagem', 'Imagem')
)

ESCOLHA_TIPO_CONTEUDO_ICONE = {
    'at_pagina': ('Pagina', '<i class="fa fa-fw fa-file-text-o"></i>'),
    'at_informe': ('Informe', '<i class="fa fa-fw fa-newspaper-o"></i>'),
    'at_agenda': ('Agenda', '<i class="fa fa-fw fa-calendar"></i>'),
    'at_link': ('Link', '<i class="fa fa-fw fa-link"></i>'),
    'at_banner': ('Banner', '<i class="fa fa-fw fa-image"></i>'),
    'at_imagem': ('Imagem', '<i class="fa fa-fw fa-file-image-o"></i>'),
    'at_organizador': ('Organizador', '<i class="fa fa-fw fa-object-group"></i>'),
    'at_menu': ('Menu', '<i class="fa fa-fw fa-th-list"></i>'),
    'at_sessao': ('Sessao', '<i class="fa fa-fw fa-tv"></i>'),
}


class Sessao(models.Model):
    url = models.SlugField(max_length=200)
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    content_type = models.CharField(max_length=20, choices=ESCOLHA_TIPO_CONTEUDO, null=True, blank=True)
    max_contents = models.PositiveIntegerField(default=1)
    evento = models.ForeignKey('Evento')
    contents = models.ManyToManyField('PortalCatalog', through='SessaoContents')
    status = models.BooleanField(default=True)

    class Meta:
        db_table = 'caninana_sessao'

    def __unicode__(self):
        return '%s' % self.titulo

    def get_absolute_url(self):
        return '/%s/%s/' % (self.evento.url, self.url)

    def save(self, **kwargs):
        if not self.url:
            self.url = 'sessao-' + slugify(self.titulo)
        super(Sessao, self).save()


class SessaoContents(models.Model):
    sessao = models.ForeignKey('Sessao')
    portal_catalog = models.ForeignKey('PortalCatalog')

    class Meta:
        db_table = 'caninana_sessao_content'


class Organizador(models.Model):
    url = models.SlugField(max_length=200, unique=True)
    titulo = models.CharField(max_length=50)
    status = models.BooleanField()
    evento = models.ForeignKey('Evento')
    content_type = models.CharField(max_length=20, choices=ESCOLHA_TIPO_CONTEUDO)

    class Meta:
        db_table = 'caninana_organizador'

    def __unicode__(self):
        return self.titulo

    @property
    def get_list_url(self):
        return '/%s/?@@list=%s' % (self.evento.url, 'at_organizador')

    def get_absolute_url(self):
        return '/%s/%s/' % (self.evento.url, self.url)

    def save(self, **kwargs):
        if not self.url:
            self.url = 'organizador-' + slugify(self.titulo)
        super(Organizador, self).save()


class Evento(models.Model):
    url = models.SlugField(max_length=200, unique=True)
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)
    criacao_at = models.DateTimeField(auto_now_add=True)
    publicacao_at = models.DateTimeField(null=True, blank=True)
    atualizacao_at = models.DateTimeField(null=True, blank=True)
    favico = models.ImageField(upload_to='evento/midias', null=True, blank=True)
    logo = models.ImageField(upload_to='evento/midias', null=True, blank=True)
    template = models.CharField(max_length=50, default='default')
    fluxo_trabalho = models.CharField(max_length=20, choices=ESCOLHA_FLUXO_TRABALHO, default='privado')
    inicio_at = models.DateTimeField(null=True, blank=True)
    encerramento_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'caninana_evento'

    def __unicode__(self):
        return self.titulo

    @property
    def edit_evento(self):
        return '/manage_main/?view=%s&action=%s' % (self.url, 'edit')

    @property
    def open_evento(self):
        return '/manage_main/?view=%s' % self.url

    @property
    def novo_evento(self):
        return '/manage_main/?action=%s' % 'new'

    @property
    def view_evento(self):
        return '/manage_main/?view=%s' % self.url

    @property
    def workflow(self):
        return '/manage_main/?view=%s&action=%s' % (self.url, 'fluxo-trabalho')

    @property
    def index_evento(self):
        return '/%s/' % self.url

    def get_absolute_url(self):
        return '/%s/' % self.url

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Evento, self).save()


class Usuario(models.Model):
    evento = models.ForeignKey(Evento, related_name='ref_eventos')
    user = models.ForeignKey(User, related_name="ref_users")
    grupo = models.CharField(max_length=50, choices=ESCOLHA_GRUPO)

    class Meta:
        db_table = 'caninana_usuario'

    def __unicode__(self):
        return self.user.get_full_name()


class Menu(models.Model):
    url = models.SlugField(max_length=200, unique=True)
    titulo = models.CharField(max_length=30)
    link = models.CharField(max_length=255, null=True, blank=True, default='#')
    menu_pai = models.ForeignKey('self', null=True, blank=True, related_name='sub_menus')
    status = models.BooleanField(default=True)
    evento = models.ForeignKey(Evento)

    class Meta:
        db_table = 'caninana_menu'

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return '/%s/%s/' % (self.evento.url, self.url)

    def save(self, **kwargs):
        if not self.url:
            self.url = 'menu-' + slugify(self.titulo)
        super(Menu, self).save()


class Content(models.Model):
    url = models.SlugField(max_length=200)
    titulo = models.CharField(max_length=255)
    descricao = models.TextField(null=True, blank=True)
    criacao_at = models.DateTimeField(auto_now_add=True)
    publicacao_at = models.DateTimeField(null=True, blank=True)
    atualizacao_at = models.DateTimeField(null=True, blank=True)
    fluxo_trabalho = models.CharField(max_length=20, choices=ESCOLHA_FLUXO_TRABALHO, default='privado')
    categoria = models.CharField(max_length=20, choices=ESCOLHA_CATEGORIA, default='publico')
    evento = models.ForeignKey(Evento)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return '/%s/%s/' % (self.evento.url, self.url)

    class Meta:
        db_table = 'caninana_content'
        abstract = True
        unique_together = (("evento", "url"),)


class Pagina(Content):
    corpo = models.TextField(null=True, blank=True)
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Pagina, self).save()

    class Meta:
        db_table = 'caninana_pagina'


class Informe(Content):
    corpo = models.TextField(null=True, blank=True)
    imagem = models.ImageField(upload_to='evento/midias/informes', null=True, blank=True)
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Informe, self).save()

    class Meta:
        db_table = 'caninana_informe'


class Agenda(Content):
    inicio_at = models.DateTimeField()
    termino_at = models.DateTimeField()
    corpo = models.TextField(null=True, blank=True)
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Agenda, self).save()

    class Meta:
        db_table = 'caninana_agenda'


# Tipo de contéudo para midias de links internos e externos
class Link(Content):
    link = models.CharField(max_length=200)
    target = models.CharField(max_length=20, choices=ESCOLHA_TARGET, default='_self')
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Link, self).save()

    class Meta:
        db_table = 'caninana_link'


# Tipo de conteúdo para midias de imagens para uso em paginas e outros
class Imagem(Content):
    imagem = models.ImageField(upload_to='imagens')
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Imagem, self).save()

    class Meta:
        db_table = 'caninana_imagem'


# Tipo de conteúdo para aprentação em destaque
class Banner(Content):
    imagem = models.ImageField(upload_to='evento/midias/banner')
    link = models.CharField(max_length=200)
    target = models.CharField(max_length=20, choices=ESCOLHA_TARGET, default='_self')
    organizador = models.ForeignKey(Organizador, null=True, blank=True)

    def save(self, **kwargs):
        if not self.url:
            self.url = slugify(self.titulo)
        super(Banner, self).save()

    class Meta:
        db_table = 'caninana_banner'


class PortalCatalog(Content):
    content_type = models.CharField(max_length=20, choices=ESCOLHA_TIPO_CONTEUDO)

    class Meta:
        db_table = 'caninana_portal_catalog'

    @property
    def get_content(self):

forms/agenda_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Agenda, Organizador

class AgendaForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)
    def __init__(self, *args, **kwargs):
        super(AgendaForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField(required=False,
            queryset=Organizador.objects.filter(content_type='at_agenda')
        )

    class Meta:
        model = Agenda
        fields = (
            'url', 'titulo', 'descricao', 'corpo', 'inicio_at', 'termino_at', 'organizador', 'categoria'
        )

        labels = {
            'url': 'URL',
            'titulo':'Título da agenda',
            'descricao':'Descrição da agenda.',
            'corpo':'Corpo da agenda.',
            'inicio_at':'Início da programação',
            'termino_at':'Termino da programação',
            'organizador':'Organizador de conteúdo',
            'categoria':'Categoria da agenda.',
        }

forms/banner_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Banner, Organizador

class BannerForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)
    def __init__(self, *args, **kwargs):
        super(BannerForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField( required=False,
            queryset=Organizador.objects.filter(content_type='at_banner')
        )

    class Meta:
        model = Banner
        fields = (
            'url', 'titulo', 'descricao', 'imagem', 'link', 'target', 'organizador', 'categoria',
        )

        labels = {
            'url': 'URL.',
            'titulo':'Título do banner.',
            'descricao':'Descrição do banner.',
            'imagem':'Imagem de apresentação.',
            'link':'Link para.',
            'target':'Opção de carregamento.',
            'organizador':'Organizador de conteúdo',
            'categoria':'Categoria.',
        }

forms/imagem_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Imagem, Organizador

class ImagemForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)
    def __init__(self, *args, **kwargs):
        super(ImagemForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField(required=False,
            queryset=Organizador.objects.filter(content_type='at_imagem')
        )

    class Meta:
        model = Imagem
        fields = (
            'url', 'titulo', 'descricao', 'imagem', 'categoria', 'organizador',
        )

        labels = {
            'url': 'URL.',
            'titulo':'Título do imagem.',
            'descricao':'Descrição do imagem.',
            'imagem':'Imagem.',
            'categoria':'Categoria.',
            'organizador':'Organizador de conteúdo'
        }

forms/informe_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Informe, Organizador

class InformeForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)
    def __init__(self, *args, **kwargs):
        super(InformeForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField(required=False,
            queryset=Organizador.objects.filter(content_type='at_informe')
        )

    class Meta:
        model = Informe
        fields = (
            'url', 'titulo', 'descricao', 'corpo', 'imagem', 'categoria', 'organizador'
        )

        labels = {
            'url': 'URL',
            'titulo':'Título do informe',
            'descricao':'Descrição do informe.',
            'corpo':'Corpo da informe.',
            'imagem': 'Imagem de destaque.',
            'categoria':'Escolha o papel da informe.',
            'organizador': 'Agregador de conteúdo'
        }

forms/link_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Link, Organizador

class LinkForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)
    def __init__(self, *args, **kwargs):
        super(LinkForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField(required=False,
            queryset=Organizador.objects.filter(content_type='at_link')
        )

    class Meta:
        model = Link
        fields = (
            'url', 'titulo', 'descricao', 'link', 'target', 'organizador', 'categoria',
        )

        labels = {
            'url':'URL',
            'titulo':'Título da link',
            'descricao':'Descrição da link.',
            'link':'Link para',
            'target':'Opção de carregamento',
            'organizador':'Organizador de conteúdo',
            'categoria':'Categoria'
        }

forms/menu_forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Menu

class MenuForm(ModelForm):
    url = forms.CharField(max_length=200, required=False)

    class Meta:
        model = Menu
        fields = (
           'url', 'titulo', 'link', 'status',
        )

        labels = {
            'url':'URL.',
            'titulo':'Título',
            'link':'Encaminhar para',
            'Status':'Habilitar'
        }

forms/pagina_form.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from django import forms

from caninana.models import Pagina, Organizador

class PaginaForm(ModelForm):

    url = forms.CharField(max_length=200, required=False)

    def __init__(self, *args, **kwargs):
        super(PaginaForm, self).__init__(*args, **kwargs)
        self.fields['organizador'] = forms.ModelChoiceField(
            queryset=Organizador.objects.filter(content_type='at_pagina'), required=False
        )

    class Meta:
        model = Pagina
        fields = (
            'url', 'titulo', 'descricao', 'corpo', 'categoria', 'organizador'
        )

        labels = {
            'url':'URL',
            'titulo':'Título da página',
            'descricao':'Descrição da página.',
            'corpo':'Corpo da página.',
            'categoria':'Escolha o papel da página.',
            'organizador': 'Agregador de conteúdo'
        }

templates/caninana/comum/agendas.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}
    <p class="lead">{{object.descricao}}</p>
    {% endif %}
    <p style="margin-top:30px;">{{object.corpo}}</p>

    <p><strong>Data de início</strong>: {{object.inicio_at}}</p>
    <p><strong>Data de encerramento</strong>: {{object.termino_at}}</p>

{% endblock content %}

templates/caninana/comum/banners.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}<p class="lead">{{object.descricao}}</p>{% endif %}
    <p style="margin-top:30px;" class="text-center"><img src="{{object.imagem.url}}" width="800"></p>
    <p style="margin-top:30px;">Link para: <a href="{{object.link}}" target="{{object.target}}">{{object.link}}</a></p>

{% endblock content %}

templates/caninana/comum/contents.html
{% extends 'caninana/index.html' %}

{% block container %}

    <div class="page-header">
        <h1>{{page_header}}{% if subtext %}<small>{{subtext}}</small>{% endif %}</h1>
    </div>

    {% block content %} {% endblock content %}

{% endblock container %}

templates/caninana/comum/forms.html
{% extends 'caninana/comum/contents.html' %}
{% load bootstrap %}

{% block content %}
    <h1>{{title}}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|bootstrap }}
        <input type="submit" value="Gravar" class="btn btn-primary" />
        {% if content_type == 'at_organizador' %}
            <a href="{{evento.get_absolute_url}}?@@list=at_organizador" class="btn btn-danger">Fechar</a>
        {% else %}
            <a href="{% if object %}{{object.get_absolute_url}}{% else %}{{evento.get_absolute_url}}{% endif %}" class="btn btn-danger">Fechar</a>
        {% endif %}
    </form>
{% endblock content %}

templates/caninana/comum/imagems.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}<p class="lead">{{object.descricao}}</p>{% endif %}
    <p style="margin-top:30px;" class="text-center"><img src="{{object.imagem.url}}" width="800"></p>

{% endblock content %}

templates/caninana/comum/informes.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}<p class="lead">{{object.descricao}}</p>{% endif %}
    <p style="margin-top:30px;">{{object.corpo}}</p>
    {% if object.imagem %}
        <p class="text-center"><img src="{{object.imagem.url}}"/></p>
    {% endif %}
{% endblock content %}

templates/caninana/comum/links.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}<p class="lead">{{object.descricao}}</p>{% endif %}

    <p style="margin-top:30px;"><a href="{{object.link}}" target="{{object.target}}">{{object.link}}</a></p>

{% endblock content %}

templates/caninana/comum/list_all_contens.html
{% extends 'caninana/comum/contents.html' %}
{% load event_tags %}

{% block content %}
    {% if objects %}
        <div class="row">
        {% has_lista_all_contents objects evento=evento %}
        </div>
    {% else %}
        <p>Nenhum contúdo encontrado</p>
    {% endif %}
{% endblock content %}

templates/caninana/comum/menus.html
{% extends 'caninana/comum/contents.html' %}
{% load event_tags %}

{% block content %}
{% if object %}
    <p>
        {% if object.menu_pai %}
            <a href="{{object.menu_pai.get_absolute_url}}">&nbsp;<i class="fa fa-reply"></i>&nbsp;Retornar nível acima&nbsp;</a>
        {% else %}
            <a href="{{object.evento.get_absolute_url}}?@@list=at_menu">&nbsp;<i class="fa fa-reply"></i>&nbsp;Retornar nível acima&nbsp;</a>
        {% endif %}&nbsp;
        <a href="{{object.get_absolute_url}}?@@createObject=at_menu"><i class="fa fa-plus-square"></i> Adicionar item ao menu</a>
    </p>

    Listar aqui seus itens de menu
    <p>
        <ul>
        {% if object.sub_menus.count > 0 %}
            {% has_bulder_menu object.sub_menus.all sistema=True %}
        {% else %}
            <li>{{object.titulo}}</li>
        {% endif %}
        </ul>
    </p>
{% else %}
<table class="table">
    <thead>
        <th>Titulo do menu</th>
        <th>Nó</th>
        <th>Link</th>
        <th>Status</th>
        <th>&nbsp&nbsp;</th>
    </thead>
    <tbody>
        {% if objects %}
            {% for object in objects %}
            <tr>
                <td>{{object.titulo}}</td>
                <td>{% if object.menu_pai == None %}Raiz{% endif %}</td>
                <td>{{object.link}}</td>
                <td>{{object.status}}</td>
                <td>
                    <a href="{{object.get_absolute_url}}?action=update"><i class="fa fa-edit"></i></a>
                    <a href="{{object.get_absolute_url}}"><i class="fa fa-tv"></i></a>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="2">Nenhum menu foi encontrada.</td></tr>
        {% endif %}
    </tbody>
</table>
{% endif %}
{% endblock content %}

templates/caninana/comum/organizadores.html
{% extends 'caninana/comum/contents.html' %}
{% load event_tags %}

{% block content %}
{% if object %}
    {% has_contents_by_organizador object %}
{% else %}
<table class="table">
    <thead>
        <th>Título</th>
        <th>Tipo de conteúdo</th>
        <th>Status</th>
        <th>&nbsp;</th>
    </thead>
    <tbody>
        {% if objects %}
            {% for object in objects %}
            <tr>
                <td>{{object.titulo}}</td>
                <td>{{object.get_content_type_display}}</td>
                <td>{{object.status}}</td>
                <td>
                    <a href="{{object.get_absolute_url}}?action=update"><i class="fa fa-edit"></i></a>
                    <a href="{{object.get_absolute_url}}"><i class="fa fa-tv"></i></a>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="2">Nenhuma categoria foi encontrada.</td></tr>
        {% endif %}
    </tbody>
</table>
{% endif %}
{% endblock content %}

templates/caninana/comum/paginas.html
{% extends 'caninana/comum/contents.html' %}

{% block content %}
    {% if object.fluxo_trabalho == 'privado' %}
    <!-- Falta definir regra de permissão. -->
    <a href="{{object.get_absolute_url}}?workflow=publicado" title="Publicar"><i class="fa  fa-thumbs-up"></i></a>
    <span class="text-danger" style="font-size:12px">
        {% if not object.publicacao_at %}
            Por: Janer Bastos de Melo -- criado em {{object.criacao_at}}
        {% else %}
            Por: Janer Bastos de Melo -- {{workflow}} em {{object.publicacao_at}}s
        {% endif %}
    </span>
    {% else %}
        <a class="text-danger" href="{{object.get_absolute_url}}?workflow=privado" title="Retirar"><i class="fa  fa-thumbs-down"></i></a>
        <span style="font-size:12px">Por: Janer Bastos de Melo -- {{workflow}} {{object.publicacao_at}}</span>
    {% endif %}

    {% if object.descricao %}<p class="lead">{{object.descricao}}</p>{% endif %}
    <p style="margin-top:30px;">{{object.corpo}}</p>
{% endblock content %}